### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'manifest_file'

### ISSUE THREAD

**Issue by meowameowameow** [meta-llama/llama-models#115]
I've followed the instructions in https://github.com/meta-llama/llama-models/blob/main/README.md to download the model, however, when I reached Step 6 `Run: llama download --source meta --model-id CHOSEN_MODEL_ID`, I encountered the following error message:
```
# llama download --source meta --model-id Meta-Llama3.1-8B-Instruct
/root/miniconda3/envs/myKV/lib/python3.10/site-packages/pydantic/_internal/_fields.py:161: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/root/miniconda3/envs/myKV/bin/llama", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/myKV/lib/python3.10/site-packages/llama_toolchain/cli/llama.py", line 54, in main
    parser.run(args)
  File "/root/miniconda3/envs/myKV/lib/python3.10/site-packages/llama_toolchain/cli/llama.py", line 48, in run
    args.func(args)
  File "/root/miniconda3/envs/myKV/lib/python3.10/site-packages/llama_toolchain/cli/download.py", line 146, in run_download_cmd
    if args.manifest_file:
AttributeError: 'Namespace' object has no attribute 'manifest_file'
```
Please advise If there is any way to fix it, thanks : )

**Comment by ashwinb** [comment]
I fixed it with https://github.com/meta-llama/llama-stack/commit/e08e963f861b9c44f80ac351c79cd9bc1c54000d, and updated the `llama-toolchain` package to v0.0.8. Please re-install it and it should fix the issues. Re-open this if it does not. Sorry!

**Comment by meowameowameow** [comment]
Thanks!
