### ISSUE TITLE
Error in download.py NameError: name 'M' is not defined

### ISSUE THREAD

**Issue by navintech14** [meta-llama/llama-models#122]
I was trying to download llama3.1-70B on my windows
`llama download --source meta --model-id Meta-Llama3.1-70B`

`Downloading `consolidated.06.pth`...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Scripts\llama.exe\__main__.py", line 7, in <module>
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\llama.py", line 54, in main
    parser.run(args)
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\llama.py", line 48, in run
    args.func(args)
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\download.py", line 174, in run_download_cmd
    _meta_download(model, meta_url)
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\download.py", line 143, in _meta_download
    asyncio.run(downloader.download())
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\download.py", line 273, in download
    f"Required: {(additional_size / M):.2f} MB"
                                    ^
NameError: name 'M' is not defined`

When stating to download I got a warning

`C:\Users\snavi\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_fields.py:161: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.`

I am not sure if this warning is relevant.

Thank you

**Comment by navintech14** [comment]
I realized I am getting this error because I do not have enough space on my disk. I am closing this Issue.

**Comment by ashwinb** [comment]
Yes the error in the error was fixed by @sisminnmaw earlier today. The packages have not been updated yet.
