### ISSUE TITLE
error when installing the llama model list

### ISSUE THREAD

**Issue by QIZHONG-coder** [meta-llama/llama-models#145]
C:\Users\rain>llama model list
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python312\Scripts\llama.exe\__main__.py", line 4, in <module>
  File "C:\python312\Lib\site-packages\llama_toolchain\cli\llama.py", line 11, in <module>
    from .stack import StackParser
  File "C:\python312\Lib\site-packages\llama_toolchain\cli\stack\__init__.py", line 7, in <module>
    from .stack import StackParser  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python312\Lib\site-packages\llama_toolchain\cli\stack\stack.py", line 12, in <module>
    from .configure import StackConfigure
  File "C:\python312\Lib\site-packages\llama_toolchain\cli\stack\configure.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by TheDamik34** [comment]
It happened to me as well on python 3.12.0. I downgraded to 3.11.0 and it worked

**Comment by varunfb** [comment]
Please try with the latest version of `llama-stack` and it should be working with both `3.12.0` and `3.11.0`. Re-open the issue with version of llama-stack being used and the output if you are still having an issue.
