### ISSUE TITLE
Why does it give an error when I run the llama model I set up, showing that cuda is wrong? But there is no problem with the configuration? Is there anyone who can teach me?

### ISSUE THREAD

**Issue by xie85** [meta-llama/llama-models#208]
(llama32xj) [2401213419@l12gpu30 conda]$ llama stack run meta-reference-gpu --port 8080
Using config `/lustre/home/2401213419/.llama/builds/conda/meta-reference-gpu-run.yaml`
Resolved 12 providers
 inner-inference => meta-reference
 inner-memory => meta-reference-00
 models => __routing_table__
 inference => __autorouted__
 inner-safety => meta-reference
 shields => __routing_table__
 safety => __autorouted__
 memory_banks => __routing_table__
 memory => __autorouted__
 agents => meta-reference
 telemetry => meta-reference
 inspect => __builtin__

Traceback (most recent call last):
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 368, in <module>
    fire.Fire(main)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 300, in main
    impls = asyncio.run(resolve_impls(config, get_provider_registry(), dist_registry))
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 191, in resolve_impls
    impl = await instantiate_provider(
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 287, in instantiate_provider
    impl = await fn(*args)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/__init__.py", line 16, in get_provider_impl
    from .inference import MetaReferenceInferenceImpl
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/inference.py", line 18, in <module>
    from .generation import Llama
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/generation.py", line 18, in <module>
    import torch
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /lustre/home/2401213419/software/miniconda3/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
Error occurred in script at line: 40

**Comment by varunfb** [comment]
This is a llama-stack issue. Can you please report this issue in [llama-stack](https://github.com/meta-llama/llama-stack/issues)?
