### ISSUE TITLE
RuntimeError: The server socket has failed to listen on any local network address. useIpv6: 0, code: -48, name: EADDRINUSE, message: address already in use

### ISSUE THREAD

**Issue by rtrad89** [meta-llama/llama-models#210]
Trying to follow the README on M1 chip, but receiving the error in the title

```bash
W1107 10:04:31.990000 8471214144 torch/distributed/elastic/multiprocessing/redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/Users/myuser/.pyenv-3-12/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/agent/server/api.py", line 680, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/agent/server/api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/agent/server/api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/agent/server/api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/.pyenv-3-12/lib/python3.12/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 66, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The server socket has failed to listen on any local network address. useIpv6: 0, code: -48, name: EADDRINUSE, message: address already in use
```

**Comment by wtz222** [comment]
Have you resolved this?

**Comment by PyyWill** [comment]
+1

**Comment by hciays** [comment]
+1

**Comment by ziko-21** [comment]
+1

**Comment by MAXNORM8650** [comment]
Did anyone solved?

**Comment by ebwendol** [comment]
Are there obvious locations where torch/cuda seeds are being set? Removing such lines fixed this error in my application.
