### ISSUE TITLE
Failures llama_models/scripts/example_chat_completion.py FAILED

### ISSUE THREAD

**Issue by ganeshkinkar** [meta-llama/llama-models#235]
fatal: not a git repository (or any of the parent directories): .git
W1204 11:52:20.957000 87930 torch/distributed/elastic/multiprocessing/redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/bin/python3.10: can't open file '/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/LLAMA/llama_models/scripts/example_chat_completion.py': [Errno 2] No such file or directory
E1204 11:52:21.101000 87930 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 2) local_rank: 0 (pid: 87931) of binary: /Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/bin/python3.10
Traceback (most recent call last):
  File "/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/ganeshkinkargiri./Desktop/Git-kyndryl/RAG_VECTOR_DB/llama_finetune_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
llama_models/scripts/example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-04_11:52:21
  host      : M7QJY5-A67EFC4A
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 87931)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by SoundDesignerToBe** [comment]
I landed at this error too after hours of download and setup
