### ISSUE TITLE
Meta-Llama-3.1-405B-Instruct-MP16 init error

### ISSUE THREAD

**Issue by surmenok** [meta-llama/llama-models#42]
Cannot instantiate 405B model.

Pseudocode below (omitting details on process group init). Running with 16 ranks to match model parallelism expected for this model ([per `model_parallel_size` in `sku_list`](https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/api/sku_list.py#L106))

```
from fairscale.nn.model_parallel.initialize import initialize_model_parallel
from model import ModelArgs, Transformer
from torch.distributed import init_process_group

init_process_group(...)
initialize_model_parallel(16)  # world_size=16

model_args = ModelArgs(**{
    "dim": 16384,
    "n_layers": 126,
    "n_heads": 128,
    "n_kv_heads": 8,
    "vocab_size": 128256,
    "ffn_dim_multiplier": 1.2,
    "multiple_of": 4096,
    "norm_eps": 1e-05,
    "rope_theta": 500000.0,
    "use_scaled_rope": True,
})
model = Transformer(model_args)
```

Error:
```
[rank15]: Traceback (most recent call last):
[rank15]:   File "/home/pavel/llama_inference.py", line 38, in <module>
[rank15]:     model = Transformer(model_args)
[rank15]:             ^^^^^^^^^^^^^^^^^^^^^^^
[rank15]:   File "/home/pavel/model.py", line 304, in __init__
[rank15]:     self.layers.append(TransformerBlock(layer_id, params))
[rank15]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank15]:   File "/home/pavel/model.py", line 268, in __init__
[rank15]:     self.attention = Attention(args)
[rank15]:                      ^^^^^^^^^^^^^^^
[rank15]:   File "/home/pavel/model.py", line 137, in __init__
[rank15]:     self.n_rep = self.n_local_heads // self.n_local_kv_heads
[rank15]:                  ~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~
[rank15]: ZeroDivisionError: integer division or modulo by zero
```

Seems like division of `n_kv_heads = 8` [here](https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/api/sku_list.py#L111) by `model_parallel_size = 16` [per this value](https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/api/sku_list.py#L106) leads to `self.n_local_kv_heads = 0`

**Comment by ashwinb** [comment]
Yes, this is a mistake indeed. Fixing it.

**Comment by ashwinb** [comment]
Fixed by https://github.com/meta-llama/llama-models/commit/f45cdfd624b98b6655540f7101d8d9cb432e631c

Thank you for reporting.
